### PR TITLE
Bart add touch events

### PR DESCRIPTION
**Pull request by WunderBart**
This ads support for result selection with touch events.

### CODE REVIEW

**Comment by nidalaa** [comment]
Works perfectly in Luna maps :+1: @stevebrownlee any chances for merge? :pray:

**Comment by stevebrownlee** [comment]
Please make sure this works in the following projects.

1. Homepage
2. Waldorf
3. Landing pages

If it works on home page, any destination page, and the booking services pages, then go ahead and merge.

**Comment by WunderBart** [comment]
I don't work on any of these apps unfortunately... 
This is a minor update, it's totally backwards compatible. It simply ads touch events to result selection. For 'pointer users' nothing changes. 
If you still need someone to test it in the apps above, could you please point me to someone who could do that?

**Comment by stevebrownlee** [comment]
I'm a bit more cautious after what happened with the control on landing pages, but after reviewing the code, I concur that the change should be compatible.

:shipit:

**Pull request merged**
