### PR TITLE
Improve triggered value detection

### PR DESCRIPTION
**Pull request by WunderBart**
This fixes search term's whitespace & newline vulnerability.

### CODE REVIEW

**Comment by stevebrownlee** [comment]
What's the best way to test this locally?

**Comment by WunderBart** [comment]
You'll have to setup Autocoplete on `<textarea>` with some fixed data for triggered searchTerm use. If it's necessary I'll build an example before merge. I'd prefer merging it first though cause :clock1: is :moneybag: :wink: 

I promise to make an example right after I'm finished with Autocomplete bump in Community :+1: 

So how's it gonna be? :smile:

**Comment by stevebrownlee** [comment]
Ok, I trust that you've fully tested it.  The code is :+1:

**Comment by WunderBart** [comment]
I will be live soon in Community - we're using it for user mentions (like this one: `@stevebrownlee`) in topic reply form. I'll let you know.

**Pull request merged**
